server:
  port: 8888

####服务网关名称
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
        # 允许注册中心获取地址
          enabled: true
      routes:
      - id: producer--route
        uri: lb://producer-service
        predicates:
        - Path=/producer/**
        filters:
        - StripPrefix=1
      - id: consumer-route
        uri: lb://consumer-service
        predicates:
        - Path=/consumer/**
        filters:
        - StripPrefix=1
    nacos:
      discovery:
        server-addr: 123.57.173.162:8848
