server:
  port: 8888

####服务网关名称
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          # 开启以服务id去注册中心上获取转发地址
          enabled: true
      routes:
        # 路由 id
      - id: provider-route
        # 基于 lb 负载均衡形式转发
        uri: lb://provider-service
        predicates:
        - Path=/provider/**
        filters:
          # 跳过一级前缀
        - StripPrefix=1
      - id: consumer-route
        uri: lb://consumer-service
        predicates:
        - Path=/api/consumer/**
        filters:
        - StripPrefix=2
    nacos:
      discovery:
        server-addr: 123.57.173.162:8848
