
spring:
  cloud:
    nacos:
      discovery:
      # nacos服务器地址
        server-addr: 123.57.173.162:8848
    sentinel:
      transport:
        dashboard: localhost:8718
      eager: true
  application:
    name: producer-service
server:
  port: 8084
