spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-route
        uri: lb://user-service
        predicates:
        - Path=/user-service/**
        filters:
        - StripPrefix=1


eureka:
 client:
   serviceUrl:
    defaultZone: http://49.233.192.8:8761/eureka/

server:
  port: 8889

